import os

from dotenv import load_dotenv
from pydantic import BaseModel, Field

from llm.embeddings import get_embeddings
from llm.groq_llm import get_structured_completion
from vectorstore.azure_ai_search import AzureAISearchVectorStore, Retriever

load_dotenv()


class FinancialMetrics(BaseModel):
    revenue: str | int | None = Field(None, alias="Revenue")
    net_income: str | int | None = Field(None, alias="Net Income")
    operating_income: str | int | None = Field(None, alias="Operating Income")
    cash_flow: str | int | None = Field(None, alias="Cash Flow from Operating Activities")
    total_assets: str | int | None = Field(None, alias="Total Assets")
    total_liabilities: str | int | None = Field(None, alias="Total Liabilities")
    risk_factors: str | list | None = Field(None, alias="Top Risk Factors")
    growth_drivers: str | list | None = Field(None, alias="Top Growth Drivers")


# One broad query dilutes the embedding across too many topics at once —
# it tends to surface sections that mention many of these words in
# passing (e.g. a table of contents) rather than the section that
# actually contains each figure. A separate, narrow query per category
# retrieves more precisely, and each category only needs a couple of
# chunks since it's targeting one specific part of the filing.
RETRIEVAL_CATEGORIES: dict[str, str] = {
    "income_statement": "total net sales revenue cost of sales gross margin operating income net income",
    "balance_sheet": "consolidated balance sheet total assets total liabilities shareholders equity",
    "cash_flow": "consolidated statement of cash flows cash generated from operating activities",
    "risk_factors": "risk factors that could materially adversely affect the business",
    "growth_drivers": "growth strategy drivers of increased revenue future opportunities"
}


def retrieve_context(
    retriever: Retriever,
    company: str,
    year: int,
    chunks_per_category: int = 4,
    max_chars_per_chunk: int = 1500
) -> str:
    """
    Retrieve financial context from the vector store, one targeted query
    per KPI category (see RETRIEVAL_CATEGORIES) rather than a single
    broad query. Results are deduplicated (the same chunk can rank for
    more than one category) and each chunk is truncated to
    max_chars_per_chunk to bound the final prompt size.

    Two distinct bugs were found here by inspecting the actual retrieved
    context (not just the final answer):

    1. Truncation cut chunks off before reaching the figure. At the old
       700-char limit, the balance sheet chunk has "Total assets" at
       char ~809 and "Total liabilities" at ~1299 (both past the cut);
       the cash flow chunk has "Cash generated by operating activities"
       at ~1070 (also past the cut). Bumping the limit to 1500 covers
       all of these with margin.

    2. `top_k` was also acting as the candidate pool size for the
       underlying Azure Search hybrid query, not just a post-hoc slice.
       `Retriever.invoke` passes `top_k` as both `k_nearest_neighbors`
       for the vector query and `top` for the keyword query, and Azure
       Search fuses the two rankings (RRF) *within that pool* before
       returning results. So `top_k=2` and `top_k=4` for the same query
       don't just differ by how many extra results you get back — they
       can return a genuinely different top-2. Confirmed empirically:
       for the income_statement query, the chunk containing "Total net
       sales"/"Operating income" (391,035 / 123,216) only enters the
       results once top_k >= 4; at top_k=2 or 3 it's absent entirely,
       so no amount of raising max_chars_per_chunk would have surfaced
       it. Raising chunks_per_category to 4 fixes this (verified: all
       six target figures are present in the assembled context at
       chunks_per_category=4, max_chars_per_chunk=1500).

    At these settings the full assembled prompt is ~17K chars, roughly
    4,400 tokens by a conservative chars/4 estimate — confirmed against
    Groq's actual reported usage to stay well under the free-tier 8000
    tokens/minute cap even with the structured-output schema added on
    top.
    """
    seen: set[str] = set()
    sections: list[str] = []

    for label, query in RETRIEVAL_CATEGORIES.items():
        documents = retriever.invoke(
            query=query,
            company=company,
            year=str(year),
            top_k=chunks_per_category
        )

        for doc in documents:
            snippet = doc.page_content[:max_chars_per_chunk]
            if snippet not in seen:
                seen.add(snippet)
                sections.append(f"[{label}]\n{snippet}")

    return "\n\n".join(sections)


def build_extraction_prompt(
    company: str,
    year: int,
    context: str
) -> str:
    """
    Build the KPI extraction prompt.
    """
    return f"""
You are an expert financial analyst.

Company: {company}
Year: {year}

Context:
{context}

Extract the following information and return it as a JSON object with
exactly these keys:

- "Revenue"
- "Net Income"
- "Operating Income"
- "Cash Flow from Operating Activities"
- "Total Assets"
- "Total Liabilities"
- "Top Risk Factors" (a list of short strings)
- "Top Growth Drivers" (a list of short strings)

Instructions:

- Use only the provided context.
- Set a key's value to null if it is not present in the context.
- Financial values must match the report exactly (numbers only, no
  currency symbols or commentary).
- Risk factors and growth drivers should be concise, one sentence each.
- Return valid JSON only, no other text.
"""


def extract_financial_metrics(
    retriever: Retriever,
    company: str,
    year: int
) -> dict:
    """
    Extract KPIs using RAG.
    """
    context = retrieve_context(
        retriever=retriever,
        company=company,
        year=year
    )

    prompt = build_extraction_prompt(
        company=company,
        year=year,
        context=context
    )

    metrics = get_structured_completion(
        prompt=prompt,
        response_model=FinancialMetrics
    )

    return metrics.model_dump()


def main() -> None:
    company = "Apple"
    year = 2024

    vector_store = AzureAISearchVectorStore(
        endpoint=os.getenv("AZURE_SEARCH_ENDPOINT"),
        api_key=os.getenv("AZURE_SEARCH_API_KEY"),
        index_name=os.getenv("AZURE_SEARCH_INDEX_NAME")
    )

    retriever = Retriever(vector_store.client, embeddings=get_embeddings())

    results = extract_financial_metrics(
        retriever=retriever,
        company=company,
        year=year
    )

    print(f"\nExtracted KPIs for {company} {year}\n")

    for key, value in results.items():
        print(f"{key}:")
        print(value)
        print("-" * 80)


if __name__ == "__main__":
    main()
